# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.define "intervac" do |intervac|
    intervac.vm.box = "ubuntu/xenial64"
    intervac.vm.network :private_network, ip: "192.168.33.21"

    intervac.vm.provision "ansible" do |ansible|
      ansible.playbook = "intervac.yml"
      ansible.verbose  = "vvv"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.customize	["modifyvm", :id, "--memory", "1024"]
  end
end
